name: Bug Report
description: Report a bug in Meridyen Sandbox
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Start the sandbox with `docker compose -f ...`
        2. Send a request to ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages or logs.
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Mode
      options:
        - Cloud
        - Hybrid
        - Air-gapped
        - Development (local)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: "e.g. 1.0.0"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Any relevant environment details.
      placeholder: |
        - OS: Ubuntu 22.04
        - Docker: 24.0.7
        - Python: 3.11.5

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output.
      render: shell
